name = "somali-health-equity-collective"
main = "src/worker.ts"
compatibility_date = "2024-01-15"

[build]
command = "npm run build:worker"

[env.production.vars]
ENVIRONMENT = "production"

[env.development.vars]
ENVIRONMENT = "development"

# Static assets
[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.txt"]

[[rules]]
type = "Data"
globs = ["**/*.pdf", "**/*.jpg", "**/*.png"]