name = "somali-health-equity-collective"
main = "src/worker.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
ENVIRONMENT = "production"

[env.development.vars]  
ENVIRONMENT = "development"

# Assets configuration for static files
[assets]
directory = "./public"
binding = "ASSETS"